import { Pokemon } from "./pokemon";

export const POKEMONS: Pokemon[] = [
  {
    id: 1,
    egg: "2 km",
    img: "http://www.serebii.net/pokemongo/pokemon/001.png",
    num: "001",
    name: "Bulbasaur",
    type: ["Grass", "Poison"],
    candy: "Bulbasaur Candy",
    height: "0.71 m",
    weight: "6.9 kg",
    avg_spawns: 69,
    spawn_time: "20:00",
    weaknesses: ["Fire", "Ice", "Flying", "Psychic"],
    candy_count: 25,
    multipliers: [1.58],
    spawn_chance: 0.69,
    next_evolution: [
      { num: "002", name: "Ivysaur" },
      { num: "003", name: "Venusaur" },
    ],
  },
  {
    id: 2,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/002.png",
    num: "002",
    name: "Ivysaur",
    type: ["Grass", "Poison"],
    candy: "Bulbasaur Candy",
    height: "0.99 m",
    weight: "13.0 kg",
    avg_spawns: 4.2,
    spawn_time: "07:00",
    weaknesses: ["Fire", "Ice", "Flying", "Psychic"],
    candy_count: 100,
    multipliers: [1.2, 1.6],
    spawn_chance: 0.042,
    next_evolution: [{ num: "003", name: "Venusaur" }],
    prev_evolution: [{ num: "001", name: "Bulbasaur" }],
  },
  {
    id: 3,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/003.png",
    num: "003",
    name: "Venusaur",
    type: ["Grass", "Poison"],
    candy: "Bulbasaur Candy",
    height: "2.01 m",
    weight: "100.0 kg",
    avg_spawns: 1.7,
    spawn_time: "11:30",
    weaknesses: ["Fire", "Ice", "Flying", "Psychic"],
    multipliers: null,
    spawn_chance: 0.017,
    prev_evolution: [
      { num: "001", name: "Bulbasaur" },
      { num: "002", name: "Ivysaur" },
    ],
  },
  {
    id: 4,
    egg: "2 km",
    img: "http://www.serebii.net/pokemongo/pokemon/004.png",
    num: "004",
    name: "Charmander",
    type: ["Fire"],
    candy: "Charmander Candy",
    height: "0.61 m",
    weight: "8.5 kg",
    avg_spawns: 25.3,
    spawn_time: "08:45",
    weaknesses: ["Water", "Ground", "Rock"],
    candy_count: 25,
    multipliers: [1.65],
    spawn_chance: 0.253,
    next_evolution: [
      { num: "005", name: "Charmeleon" },
      { num: "006", name: "Charizard" },
    ],
  },
  {
    id: 5,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/005.png",
    num: "005",
    name: "Charmeleon",
    type: ["Fire"],
    candy: "Charmander Candy",
    height: "1.09 m",
    weight: "19.0 kg",
    avg_spawns: 1.2,
    spawn_time: "19:00",
    weaknesses: ["Water", "Ground", "Rock"],
    candy_count: 100,
    multipliers: [1.79],
    spawn_chance: 0.012,
    next_evolution: [{ num: "006", name: "Charizard" }],
    prev_evolution: [{ num: "004", name: "Charmander" }],
  },
  {
    id: 6,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/006.png",
    num: "006",
    name: "Charizard",
    type: ["Fire", "Flying"],
    candy: "Charmander Candy",
    height: "1.70 m",
    weight: "90.5 kg",
    avg_spawns: 0.31,
    spawn_time: "13:34",
    weaknesses: ["Water", "Electric", "Rock"],
    multipliers: null,
    spawn_chance: 0.0031,
    prev_evolution: [
      { num: "004", name: "Charmander" },
      { num: "005", name: "Charmeleon" },
    ],
  },
  {
    id: 7,
    egg: "2 km",
    img: "http://www.serebii.net/pokemongo/pokemon/007.png",
    num: "007",
    name: "Squirtle",
    type: ["Water"],
    candy: "Squirtle Candy",
    height: "0.51 m",
    weight: "9.0 kg",
    avg_spawns: 58,
    spawn_time: "04:25",
    weaknesses: ["Electric", "Grass"],
    candy_count: 25,
    multipliers: [2.1],
    spawn_chance: 0.58,
    next_evolution: [
      { num: "008", name: "Wartortle" },
      { num: "009", name: "Blastoise" },
    ],
  },
  {
    id: 8,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/008.png",
    num: "008",
    name: "Wartortle",
    type: ["Water"],
    candy: "Squirtle Candy",
    height: "0.99 m",
    weight: "22.5 kg",
    avg_spawns: 3.4,
    spawn_time: "07:02",
    weaknesses: ["Electric", "Grass"],
    candy_count: 100,
    multipliers: [1.4],
    spawn_chance: 0.034,
    next_evolution: [{ num: "009", name: "Blastoise" }],
    prev_evolution: [{ num: "007", name: "Squirtle" }],
  },
  {
    id: 9,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/009.png",
    num: "009",
    name: "Blastoise",
    type: ["Water"],
    candy: "Squirtle Candy",
    height: "1.60 m",
    weight: "85.5 kg",
    avg_spawns: 0.67,
    spawn_time: "00:06",
    weaknesses: ["Electric", "Grass"],
    multipliers: null,
    spawn_chance: 0.0067,
    prev_evolution: [
      { num: "007", name: "Squirtle" },
      { num: "008", name: "Wartortle" },
    ],
  },
  {
    id: 10,
    egg: "2 km",
    img: "http://www.serebii.net/pokemongo/pokemon/010.png",
    num: "010",
    name: "Caterpie",
    type: ["Bug"],
    candy: "Caterpie Candy",
    height: "0.30 m",
    weight: "2.9 kg",
    avg_spawns: 303.2,
    spawn_time: "16:35",
    weaknesses: ["Fire", "Flying", "Rock"],
    candy_count: 12,
    multipliers: [1.05],
    spawn_chance: 3.032,
    next_evolution: [
      { num: "011", name: "Metapod" },
      { num: "012", name: "Butterfree" },
    ],
  },
  {
    id: 11,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/011.png",
    num: "011",
    name: "Metapod",
    type: ["Bug"],
    candy: "Caterpie Candy",
    height: "0.71 m",
    weight: "9.9 kg",
    avg_spawns: 18.7,
    spawn_time: "02:11",
    weaknesses: ["Fire", "Flying", "Rock"],
    candy_count: 50,
    multipliers: [3.55, 3.79],
    spawn_chance: 0.187,
    next_evolution: [{ num: "012", name: "Butterfree" }],
    prev_evolution: [{ num: "010", name: "Caterpie" }],
  },
  {
    id: 12,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/012.png",
    num: "012",
    name: "Butterfree",
    type: ["Bug", "Flying"],
    candy: "Caterpie Candy",
    height: "1.09 m",
    weight: "32.0 kg",
    avg_spawns: 2.2,
    spawn_time: "05:23",
    weaknesses: ["Fire", "Electric", "Ice", "Flying", "Rock"],
    multipliers: null,
    spawn_chance: 0.022,
    prev_evolution: [
      { num: "010", name: "Caterpie" },
      { num: "011", name: "Metapod" },
    ],
  },
  {
    id: 13,
    egg: "2 km",
    img: "http://www.serebii.net/pokemongo/pokemon/013.png",
    num: "013",
    name: "Weedle",
    type: ["Bug", "Poison"],
    candy: "Weedle Candy",
    height: "0.30 m",
    weight: "3.2 kg",
    avg_spawns: 712,
    spawn_time: "02:21",
    weaknesses: ["Fire", "Flying", "Psychic", "Rock"],
    candy_count: 12,
    multipliers: [1.01, 1.09],
    spawn_chance: 7.12,
    next_evolution: [
      { num: "014", name: "Kakuna" },
      { num: "015", name: "Beedrill" },
    ],
  },
  {
    id: 14,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/014.png",
    num: "014",
    name: "Kakuna",
    type: ["Bug", "Poison"],
    candy: "Weedle Candy",
    height: "0.61 m",
    weight: "10.0 kg",
    avg_spawns: 44,
    spawn_time: "02:30",
    weaknesses: ["Fire", "Flying", "Psychic", "Rock"],
    candy_count: 50,
    multipliers: [3.01, 3.41],
    spawn_chance: 0.44,
    next_evolution: [{ num: "015", name: "Beedrill" }],
    prev_evolution: [{ num: "013", name: "Weedle" }],
  },
  {
    id: 15,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/015.png",
    num: "015",
    name: "Beedrill",
    type: ["Bug", "Poison"],
    candy: "Weedle Candy",
    height: "0.99 m",
    weight: "29.5 kg",
    avg_spawns: 5.1,
    spawn_time: "04:50",
    weaknesses: ["Fire", "Flying", "Psychic", "Rock"],
    multipliers: null,
    spawn_chance: 0.051,
    prev_evolution: [
      { num: "013", name: "Weedle" },
      { num: "014", name: "Kakuna" },
    ],
  },
  {
    id: 16,
    egg: "2 km",
    img: "http://www.serebii.net/pokemongo/pokemon/016.png",
    num: "016",
    name: "Pidgey",
    type: ["Normal", "Flying"],
    candy: "Pidgey Candy",
    height: "0.30 m",
    weight: "1.8 kg",
    avg_spawns: 1.598,
    spawn_time: "01:34",
    weaknesses: ["Electric", "Rock"],
    candy_count: 12,
    multipliers: [1.71, 1.92],
    spawn_chance: 15.98,
    next_evolution: [
      { num: "017", name: "Pidgeotto" },
      { num: "018", name: "Pidgeot" },
    ],
  },
  {
    id: 17,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/017.png",
    num: "017",
    name: "Pidgeotto",
    type: ["Normal", "Flying"],
    candy: "Pidgey Candy",
    height: "1.09 m",
    weight: "30.0 kg",
    avg_spawns: 102,
    spawn_time: "01:30",
    weaknesses: ["Electric", "Rock"],
    candy_count: 50,
    multipliers: [1.79],
    spawn_chance: 1.02,
    next_evolution: [{ num: "018", name: "Pidgeot" }],
    prev_evolution: [{ num: "016", name: "Pidgey" }],
  },
  {
    id: 18,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/018.png",
    num: "018",
    name: "Pidgeot",
    type: ["Normal", "Flying"],
    candy: "Pidgey Candy",
    height: "1.50 m",
    weight: "39.5 kg",
    avg_spawns: 13,
    spawn_time: "01:50",
    weaknesses: ["Electric", "Rock"],
    multipliers: null,
    spawn_chance: 0.13,
    prev_evolution: [
      { num: "016", name: "Pidgey" },
      { num: "017", name: "Pidgeotto" },
    ],
  },
  {
    id: 19,
    egg: "2 km",
    img: "http://www.serebii.net/pokemongo/pokemon/019.png",
    num: "019",
    name: "Rattata",
    type: ["Normal"],
    candy: "Rattata Candy",
    height: "0.30 m",
    weight: "3.5 kg",
    avg_spawns: 1.305,
    spawn_time: "01:55",
    weaknesses: ["Fighting"],
    candy_count: 25,
    multipliers: [2.55, 2.73],
    spawn_chance: 13.05,
    next_evolution: [{ num: "020", name: "Raticate" }],
  },
  {
    id: 20,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/020.png",
    num: "020",
    name: "Raticate",
    type: ["Normal"],
    candy: "Rattata Candy",
    height: "0.71 m",
    weight: "18.5 kg",
    avg_spawns: 41,
    spawn_time: "01:56",
    weaknesses: ["Fighting"],
    multipliers: null,
    spawn_chance: 0.41,
    prev_evolution: [{ num: "019", name: "Rattata" }],
  },
  {
    id: 21,
    egg: "2 km",
    img: "http://www.serebii.net/pokemongo/pokemon/021.png",
    num: "021",
    name: "Spearow",
    type: ["Normal", "Flying"],
    candy: "Spearow Candy",
    height: "0.30 m",
    weight: "2.0 kg",
    avg_spawns: 473,
    spawn_time: "12:25",
    weaknesses: ["Electric", "Rock"],
    candy_count: 50,
    multipliers: [2.66, 2.68],
    spawn_chance: 4.73,
    next_evolution: [{ num: "022", name: "Fearow" }],
  },
  {
    id: 22,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/022.png",
    num: "022",
    name: "Fearow",
    type: ["Normal", "Flying"],
    candy: "Spearow Candy",
    height: "1.19 m",
    weight: "38.0 kg",
    avg_spawns: 15,
    spawn_time: "01:11",
    weaknesses: ["Electric", "Rock"],
    multipliers: null,
    spawn_chance: 0.15,
    prev_evolution: [{ num: "021", name: "Spearow" }],
  },
  {
    id: 23,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/023.png",
    num: "023",
    name: "Ekans",
    type: ["Poison"],
    candy: "Ekans Candy",
    height: "2.01 m",
    weight: "6.9 kg",
    avg_spawns: 227,
    spawn_time: "12:20",
    weaknesses: ["Ground", "Psychic"],
    candy_count: 50,
    multipliers: [2.21, 2.27],
    spawn_chance: 2.27,
    next_evolution: [{ num: "024", name: "Arbok" }],
  },
  {
    id: 24,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/024.png",
    num: "024",
    name: "Arbok",
    type: ["Poison"],
    candy: "Ekans Candy",
    height: "3.51 m",
    weight: "65.0 kg",
    avg_spawns: 7.2,
    spawn_time: "01:50",
    weaknesses: ["Ground", "Psychic"],
    multipliers: null,
    spawn_chance: 0.072,
    prev_evolution: [{ num: "023", name: "Ekans" }],
  },
  {
    id: 25,
    egg: "2 km",
    img: "http://www.serebii.net/pokemongo/pokemon/025.png",
    num: "025",
    name: "Pikachu",
    type: ["Electric"],
    candy: "Pikachu Candy",
    height: "0.41 m",
    weight: "6.0 kg",
    avg_spawns: 21,
    spawn_time: "04:00",
    weaknesses: ["Ground"],
    candy_count: 50,
    multipliers: [2.34],
    spawn_chance: 0.21,
    next_evolution: [{ num: "026", name: "Raichu" }],
  },
  {
    id: 26,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/026.png",
    num: "026",
    name: "Raichu",
    type: ["Electric"],
    candy: "Pikachu Candy",
    height: "0.79 m",
    weight: "30.0 kg",
    avg_spawns: 0.76,
    spawn_time: "23:58",
    weaknesses: ["Ground"],
    multipliers: null,
    spawn_chance: 0.0076,
    prev_evolution: [{ num: "025", name: "Pikachu" }],
  },
  {
    id: 27,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/027.png",
    num: "027",
    name: "Sandshrew",
    type: ["Ground"],
    candy: "Sandshrew Candy",
    height: "0.61 m",
    weight: "12.0 kg",
    avg_spawns: 111,
    spawn_time: "01:58",
    weaknesses: ["Water", "Grass", "Ice"],
    candy_count: 50,
    multipliers: [2.45],
    spawn_chance: 1.11,
    next_evolution: [{ num: "028", name: "Sandslash" }],
  },
  {
    id: 28,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/028.png",
    num: "028",
    name: "Sandslash",
    type: ["Ground"],
    candy: "Sandshrew Candy",
    height: "0.99 m",
    weight: "29.5 kg",
    avg_spawns: 3.7,
    spawn_time: "12:34",
    weaknesses: ["Water", "Grass", "Ice"],
    multipliers: null,
    spawn_chance: 0.037,
    prev_evolution: [{ num: "027", name: "Sandshrew" }],
  },
  {
    id: 29,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/029.png",
    num: "029",
    name: "Nidoran ♀",
    type: ["Poison"],
    candy: "Nidoran ♀ (Female) Candy",
    height: "0.41 m",
    weight: "7.0 kg",
    avg_spawns: 138,
    spawn_time: "01:51",
    weaknesses: ["Ground", "Psychic"],
    candy_count: 25,
    multipliers: [1.63, 2.48],
    spawn_chance: 1.38,
    next_evolution: [
      { num: "030", name: "Nidorina" },
      { num: "031", name: "Nidoqueen" },
    ],
  },
  {
    id: 30,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/030.png",
    num: "030",
    name: "Nidorina",
    type: ["Poison"],
    candy: "Nidoran ♀ (Female) Candy",
    height: "0.79 m",
    weight: "20.0 kg",
    avg_spawns: 8.8,
    spawn_time: "07:22",
    weaknesses: ["Ground", "Psychic"],
    candy_count: 100,
    multipliers: [1.83, 2.48],
    spawn_chance: 0.088,
    next_evolution: [{ num: "031", name: "Nidoqueen" }],
    prev_evolution: [{ num: "029", name: "Nidoran(Female)" }],
  },
  {
    id: 31,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/031.png",
    num: "031",
    name: "Nidoqueen",
    type: ["Poison", "Ground"],
    candy: "Nidoran ♀ (Female) Candy",
    height: "1.30 m",
    weight: "60.0 kg",
    avg_spawns: 1.2,
    spawn_time: "12:35",
    weaknesses: ["Water", "Ice", "Ground", "Psychic"],
    multipliers: null,
    spawn_chance: 0.012,
    prev_evolution: [
      { num: "029", name: "Nidoran(Female)" },
      { num: "030", name: "Nidorina" },
    ],
  },
  {
    id: 32,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/032.png",
    num: "032",
    name: "Nidoran ♂",
    type: ["Poison"],
    candy: "Nidoran ♂ (Male) Candy",
    height: "0.51 m",
    weight: "9.0 kg",
    avg_spawns: 131,
    spawn_time: "01:12",
    weaknesses: ["Ground", "Psychic"],
    candy_count: 25,
    multipliers: [1.64, 1.7],
    spawn_chance: 1.31,
    next_evolution: [
      { num: "033", name: "Nidorino" },
      { num: "034", name: "Nidoking" },
    ],
  },
  {
    id: 33,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/033.png",
    num: "033",
    name: "Nidorino",
    type: ["Poison"],
    candy: "Nidoran ♂ (Male) Candy",
    height: "0.89 m",
    weight: "19.5 kg",
    avg_spawns: 8.3,
    spawn_time: "09:02",
    weaknesses: ["Ground", "Psychic"],
    candy_count: 100,
    multipliers: [1.83],
    spawn_chance: 0.083,
    next_evolution: [{ num: "034", name: "Nidoking" }],
    prev_evolution: [{ num: "032", name: "Nidoran(Male)" }],
  },
  {
    id: 34,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/034.png",
    num: "034",
    name: "Nidoking",
    type: ["Poison", "Ground"],
    candy: "Nidoran ♂ (Male) Candy",
    height: "1.40 m",
    weight: "62.0 kg",
    avg_spawns: 1.7,
    spawn_time: "12:16",
    weaknesses: ["Water", "Ice", "Ground", "Psychic"],
    multipliers: null,
    spawn_chance: 0.017,
    prev_evolution: [
      { num: "032", name: "Nidoran(Male)" },
      { num: "033", name: "Nidorino" },
    ],
  },
  {
    id: 35,
    egg: "2 km",
    img: "http://www.serebii.net/pokemongo/pokemon/035.png",
    num: "035",
    name: "Clefairy",
    type: ["Normal"],
    candy: "Clefairy Candy",
    height: "0.61 m",
    weight: "7.5 kg",
    avg_spawns: 92,
    spawn_time: "03:30",
    weaknesses: ["Fighting"],
    candy_count: 50,
    multipliers: [2.03, 2.14],
    spawn_chance: 0.92,
    next_evolution: [{ num: "036", name: "Clefable" }],
  },
  {
    id: 36,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/036.png",
    num: "036",
    name: "Clefable",
    type: ["Normal"],
    candy: "Clefairy Candy",
    height: "1.30 m",
    weight: "40.0 kg",
    avg_spawns: 1.2,
    spawn_time: "03:29",
    weaknesses: ["Fighting"],
    multipliers: null,
    spawn_chance: 0.012,
    prev_evolution: [{ num: "035", name: "Clefairy" }],
  },
  {
    id: 37,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/037.png",
    num: "037",
    name: "Vulpix",
    type: ["Fire"],
    candy: "Vulpix Candy",
    height: "0.61 m",
    weight: "9.9 kg",
    avg_spawns: 22,
    spawn_time: "13:43",
    weaknesses: ["Water", "Ground", "Rock"],
    candy_count: 50,
    multipliers: [2.74, 2.81],
    spawn_chance: 0.22,
    next_evolution: [{ num: "038", name: "Ninetales" }],
  },
  {
    id: 38,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/038.png",
    num: "038",
    name: "Ninetales",
    type: ["Fire"],
    candy: "Vulpix Candy",
    height: "1.09 m",
    weight: "19.9 kg",
    avg_spawns: 0.77,
    spawn_time: "01:32",
    weaknesses: ["Water", "Ground", "Rock"],
    multipliers: null,
    spawn_chance: 0.0077,
    prev_evolution: [{ num: "037", name: "Vulpix" }],
  },
  {
    id: 39,
    egg: "2 km",
    img: "http://www.serebii.net/pokemongo/pokemon/039.png",
    num: "039",
    name: "Jigglypuff",
    type: ["Normal"],
    candy: "Jigglypuff Candy",
    height: "0.51 m",
    weight: "5.5 kg",
    avg_spawns: 39,
    spawn_time: "08:46",
    weaknesses: ["Fighting"],
    candy_count: 50,
    multipliers: [1.85],
    spawn_chance: 0.39,
    next_evolution: [{ num: "040", name: "Wigglytuff" }],
  },
  {
    id: 40,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/040.png",
    num: "040",
    name: "Wigglytuff",
    type: ["Normal"],
    candy: "Jigglypuff Candy",
    height: "0.99 m",
    weight: "12.0 kg",
    avg_spawns: 1.8,
    spawn_time: "12:28",
    weaknesses: ["Fighting"],
    multipliers: null,
    spawn_chance: 0.018,
    prev_evolution: [{ num: "039", name: "Jigglypuff" }],
  },
  {
    id: 41,
    egg: "2 km",
    img: "http://www.serebii.net/pokemongo/pokemon/041.png",
    num: "041",
    name: "Zubat",
    type: ["Poison", "Flying"],
    candy: "Zubat Candy",
    height: "0.79 m",
    weight: "7.5 kg",
    avg_spawns: 652,
    spawn_time: "12:28",
    weaknesses: ["Electric", "Ice", "Psychic", "Rock"],
    candy_count: 50,
    multipliers: [2.6, 3.67],
    spawn_chance: 6.52,
    next_evolution: [{ num: "042", name: "Golbat" }],
  },
  {
    id: 42,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/042.png",
    num: "042",
    name: "Golbat",
    type: ["Poison", "Flying"],
    candy: "Zubat Candy",
    height: "1.60 m",
    weight: "55.0 kg",
    avg_spawns: 42,
    spawn_time: "02:15",
    weaknesses: ["Electric", "Ice", "Psychic", "Rock"],
    multipliers: null,
    spawn_chance: 0.42,
    prev_evolution: [{ num: "041", name: "Zubat" }],
  },
  {
    id: 43,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/043.png",
    num: "043",
    name: "Oddish",
    type: ["Grass", "Poison"],
    candy: "Oddish Candy",
    height: "0.51 m",
    weight: "5.4 kg",
    avg_spawns: 102,
    spawn_time: "03:58",
    weaknesses: ["Fire", "Ice", "Flying", "Psychic"],
    candy_count: 25,
    multipliers: [1.5],
    spawn_chance: 1.02,
    next_evolution: [
      { num: "044", name: "Gloom" },
      { num: "045", name: "Vileplume" },
    ],
  },
  {
    id: 44,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/044.png",
    num: "044",
    name: "Gloom",
    type: ["Grass", "Poison"],
    candy: "Oddish Candy",
    height: "0.79 m",
    weight: "8.6 kg",
    avg_spawns: 6.4,
    spawn_time: "11:33",
    weaknesses: ["Fire", "Ice", "Flying", "Psychic"],
    candy_count: 100,
    multipliers: [1.49],
    spawn_chance: 0.064,
    next_evolution: [{ num: "045", name: "Vileplume" }],
    prev_evolution: [{ num: "043", name: "Oddish" }],
  },
  {
    id: 45,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/045.png",
    num: "045",
    name: "Vileplume",
    type: ["Grass", "Poison"],
    candy: "Oddish Candy",
    height: "1.19 m",
    weight: "18.6 kg",
    avg_spawns: 0.97,
    spawn_time: "23:58",
    weaknesses: ["Fire", "Ice", "Flying", "Psychic"],
    multipliers: null,
    spawn_chance: 0.0097,
    prev_evolution: [
      { num: "043", name: "Oddish" },
      { num: "044", name: "Gloom" },
    ],
  },
  {
    id: 46,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/046.png",
    num: "046",
    name: "Paras",
    type: ["Bug", "Grass"],
    candy: "Paras Candy",
    height: "0.30 m",
    weight: "5.4 kg",
    avg_spawns: 236,
    spawn_time: "01:42",
    weaknesses: ["Fire", "Ice", "Poison", "Flying", "Bug", "Rock"],
    candy_count: 50,
    multipliers: [2.02],
    spawn_chance: 2.36,
    next_evolution: [{ num: "047", name: "Parasect" }],
  },
  {
    id: 47,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/047.png",
    num: "047",
    name: "Parasect",
    type: ["Bug", "Grass"],
    candy: "Paras Candy",
    height: "0.99 m",
    weight: "29.5 kg",
    avg_spawns: 7.4,
    spawn_time: "01:22",
    weaknesses: ["Fire", "Ice", "Poison", "Flying", "Bug", "Rock"],
    multipliers: null,
    spawn_chance: 0.074,
    prev_evolution: [{ num: "046", name: "Paras" }],
  },
  {
    id: 48,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/048.png",
    num: "048",
    name: "Venonat",
    type: ["Bug", "Poison"],
    candy: "Venonat Candy",
    height: "0.99 m",
    weight: "30.0 kg",
    avg_spawns: 228,
    spawn_time: "02:31",
    weaknesses: ["Fire", "Flying", "Psychic", "Rock"],
    candy_count: 50,
    multipliers: [1.86, 1.9],
    spawn_chance: 2.28,
    next_evolution: [{ num: "049", name: "Venomoth" }],
  },
  {
    id: 49,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/049.png",
    num: "049",
    name: "Venomoth",
    type: ["Bug", "Poison"],
    candy: "Venonat Candy",
    height: "1.50 m",
    weight: "12.5 kg",
    avg_spawns: 7.2,
    spawn_time: "23:40",
    weaknesses: ["Fire", "Flying", "Psychic", "Rock"],
    multipliers: null,
    spawn_chance: 0.072,
    prev_evolution: [{ num: "048", name: "Venonat" }],
  },
  {
    id: 50,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/050.png",
    num: "050",
    name: "Diglett",
    type: ["Ground"],
    candy: "Diglett Candy",
    height: "0.20 m",
    weight: "0.8 kg",
    avg_spawns: 40,
    spawn_time: "02:22",
    weaknesses: ["Water", "Grass", "Ice"],
    candy_count: 50,
    multipliers: [2.69],
    spawn_chance: 0.4,
    next_evolution: [{ num: "051", name: "Dugtrio" }],
  },
  {
    id: 51,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/051.png",
    num: "051",
    name: "Dugtrio",
    type: ["Ground"],
    candy: "Dugtrio",
    height: "0.71 m",
    weight: "33.3 kg",
    avg_spawns: 1.4,
    spawn_time: "12:37",
    weaknesses: ["Water", "Grass", "Ice"],
    multipliers: null,
    spawn_chance: 0.014,
    prev_evolution: [{ num: "050", name: "Diglett" }],
  },
  {
    id: 52,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/052.png",
    num: "052",
    name: "Meowth",
    type: ["Normal"],
    candy: "Meowth Candy",
    height: "0.41 m",
    weight: "4.2 kg",
    avg_spawns: 86,
    spawn_time: "02:54",
    weaknesses: ["Fighting"],
    candy_count: 50,
    multipliers: [1.98],
    spawn_chance: 0.86,
    next_evolution: [{ num: "053", name: "Persian" }],
  },
  {
    id: 53,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/053.png",
    num: "053",
    name: "Persian",
    type: ["Normal"],
    candy: "Meowth Candy",
    height: "0.99 m",
    weight: "32.0 kg",
    avg_spawns: 2.2,
    spawn_time: "02:44",
    weaknesses: ["Fighting"],
    multipliers: null,
    spawn_chance: 0.022,
    prev_evolution: [{ num: "052", name: "Meowth" }],
  },
  {
    id: 54,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/054.png",
    num: "054",
    name: "Psyduck",
    type: ["Water"],
    candy: "Psyduck Candy",
    height: "0.79 m",
    weight: "19.6 kg",
    avg_spawns: 254,
    spawn_time: "03:41",
    weaknesses: ["Electric", "Grass"],
    candy_count: 50,
    multipliers: [2.27],
    spawn_chance: 2.54,
    next_evolution: [{ num: "055", name: "Golduck" }],
  },
  {
    id: 55,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/055.png",
    num: "055",
    name: "Golduck",
    type: ["Water"],
    candy: "Psyduck Candy",
    height: "1.70 m",
    weight: "76.6 kg",
    avg_spawns: 8.7,
    spawn_time: "23:06",
    weaknesses: ["Electric", "Grass"],
    multipliers: null,
    spawn_chance: 0.087,
    prev_evolution: [{ num: "054", name: "Psyduck" }],
  },
  {
    id: 56,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/056.png",
    num: "056",
    name: "Mankey",
    type: ["Fighting"],
    candy: "Mankey Candy",
    height: "0.51 m",
    weight: "28.0 kg",
    avg_spawns: 92,
    spawn_time: "12:52",
    weaknesses: ["Flying", "Psychic", "Fairy"],
    candy_count: 50,
    multipliers: [2.17, 2.28],
    spawn_chance: 0.92,
    next_evolution: [{ num: "057", name: "Primeape" }],
  },
  {
    id: 57,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/057.png",
    num: "057",
    name: "Primeape",
    type: ["Fighting"],
    candy: "Mankey Candy",
    height: "0.99 m",
    weight: "32.0 kg",
    avg_spawns: 3.1,
    spawn_time: "12:33",
    weaknesses: ["Flying", "Psychic", "Fairy"],
    multipliers: null,
    spawn_chance: 0.031,
    prev_evolution: [{ num: "056", name: "Mankey" }],
  },
  {
    id: 58,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/058.png",
    num: "058",
    name: "Growlithe",
    type: ["Fire"],
    candy: "Growlithe Candy",
    height: "0.71 m",
    weight: "19.0 kg",
    avg_spawns: 92,
    spawn_time: "03:57",
    weaknesses: ["Water", "Ground", "Rock"],
    candy_count: 50,
    multipliers: [2.31, 2.36],
    spawn_chance: 0.92,
    next_evolution: [{ num: "059", name: "Arcanine" }],
  },
  {
    id: 59,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/059.png",
    num: "059",
    name: "Arcanine",
    type: ["Fire"],
    candy: "Growlithe Candy",
    height: "1.91 m",
    weight: "155.0 kg",
    avg_spawns: 1.7,
    spawn_time: "03:11",
    weaknesses: ["Water", "Ground", "Rock"],
    multipliers: null,
    spawn_chance: 0.017,
    prev_evolution: [{ num: "058", name: "Growlithe" }],
  },
  {
    id: 60,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/060.png",
    num: "060",
    name: "Poliwag",
    type: ["Water"],
    candy: "Poliwag Candy",
    height: "0.61 m",
    weight: "12.4 kg",
    avg_spawns: 219,
    spawn_time: "03:40",
    weaknesses: ["Electric", "Grass"],
    candy_count: 25,
    multipliers: [1.72, 1.73],
    spawn_chance: 2.19,
    next_evolution: [
      { num: "061", name: "Poliwhirl" },
      { num: "062", name: "Poliwrath" },
    ],
  },
  {
    id: 61,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/061.png",
    num: "061",
    name: "Poliwhirl",
    type: ["Water"],
    candy: "Poliwag Candy",
    height: "0.99 m",
    weight: "20.0 kg",
    avg_spawns: 13,
    spawn_time: "09:14",
    weaknesses: ["Electric", "Grass"],
    candy_count: 100,
    multipliers: [1.95],
    spawn_chance: 0.13,
    next_evolution: [{ num: "062", name: "Poliwrath" }],
    prev_evolution: [{ num: "060", name: "Poliwag" }],
  },
  {
    id: 62,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/062.png",
    num: "062",
    name: "Poliwrath",
    type: ["Water", "Fighting"],
    candy: "Poliwag Candy",
    height: "1.30 m",
    weight: "54.0 kg",
    avg_spawns: 1.1,
    spawn_time: "01:32",
    weaknesses: ["Electric", "Grass", "Flying", "Psychic", "Fairy"],
    multipliers: null,
    spawn_chance: 0.011,
    prev_evolution: [
      { num: "060", name: "Poliwag" },
      { num: "061", name: "Poliwhirl" },
    ],
  },
  {
    id: 63,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/063.png",
    num: "063",
    name: "Abra",
    type: ["Psychic"],
    candy: "Abra Candy",
    height: "0.89 m",
    weight: "19.5 kg",
    avg_spawns: 42,
    spawn_time: "04:30",
    weaknesses: ["Bug", "Ghost", "Dark"],
    candy_count: 25,
    multipliers: [1.36, 1.95],
    spawn_chance: 0.42,
    next_evolution: [
      { num: "064", name: "Kadabra" },
      { num: "065", name: "Alakazam" },
    ],
  },
  {
    id: 64,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/064.png",
    num: "064",
    name: "Kadabra",
    type: ["Psychic"],
    candy: "Abra Candy",
    height: "1.30 m",
    weight: "56.5 kg",
    avg_spawns: 2.7,
    spawn_time: "11:25",
    weaknesses: ["Bug", "Ghost", "Dark"],
    candy_count: 100,
    multipliers: [1.4],
    spawn_chance: 0.027,
    next_evolution: [{ num: "065", name: "Alakazam" }],
    prev_evolution: [{ num: "063", name: "Abra" }],
  },
  {
    id: 65,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/065.png",
    num: "065",
    name: "Alakazam",
    type: ["Psychic"],
    candy: "Abra Candy",
    height: "1.50 m",
    weight: "48.0 kg",
    avg_spawns: 0.73,
    spawn_time: "12:33",
    weaknesses: ["Bug", "Ghost", "Dark"],
    multipliers: null,
    spawn_chance: 0.0073,
    prev_evolution: [
      { num: "063", name: "Abra" },
      { num: "064", name: "Kadabra" },
    ],
  },
  {
    id: 66,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/066.png",
    num: "066",
    name: "Machop",
    type: ["Fighting"],
    candy: "Machop Candy",
    height: "0.79 m",
    weight: "19.5 kg",
    avg_spawns: 49,
    spawn_time: "01:55",
    weaknesses: ["Flying", "Psychic", "Fairy"],
    candy_count: 25,
    multipliers: [1.64, 1.65],
    spawn_chance: 0.49,
    next_evolution: [
      { num: "067", name: "Machoke" },
      { num: "068", name: "Machamp" },
    ],
  },
  {
    id: 67,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/067.png",
    num: "067",
    name: "Machoke",
    type: ["Fighting"],
    candy: "Machop Candy",
    height: "1.50 m",
    weight: "70.5 kg",
    avg_spawns: 3.4,
    spawn_time: "10:32",
    weaknesses: ["Flying", "Psychic", "Fairy"],
    candy_count: 100,
    multipliers: [1.7],
    spawn_chance: 0.034,
    next_evolution: [{ num: "068", name: "Machamp" }],
    prev_evolution: [{ num: "066", name: "Machop" }],
  },
  {
    id: 68,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/068.png",
    num: "068",
    name: "Machamp",
    type: ["Fighting"],
    candy: "Machop Candy",
    height: "1.60 m",
    weight: "130.0 kg",
    avg_spawns: 0.68,
    spawn_time: "02:55",
    weaknesses: ["Flying", "Psychic", "Fairy"],
    multipliers: null,
    spawn_chance: 0.0068,
    prev_evolution: [
      { num: "066", name: "Machop" },
      { num: "067", name: "Machoke" },
    ],
  },
  {
    id: 69,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/069.png",
    num: "069",
    name: "Bellsprout",
    type: ["Grass", "Poison"],
    candy: "Bellsprout Candy",
    height: "0.71 m",
    weight: "4.0 kg",
    avg_spawns: 115,
    spawn_time: "04:10",
    weaknesses: ["Fire", "Ice", "Flying", "Psychic"],
    candy_count: 25,
    multipliers: [1.57],
    spawn_chance: 1.15,
    next_evolution: [
      { num: "070", name: "Weepinbell" },
      { num: "071", name: "Victreebel" },
    ],
  },
  {
    id: 70,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/070.png",
    num: "070",
    name: "Weepinbell",
    type: ["Grass", "Poison"],
    candy: "Bellsprout Candy",
    height: "0.99 m",
    weight: "6.4 kg",
    avg_spawns: 7.2,
    spawn_time: "09:45",
    weaknesses: ["Fire", "Ice", "Flying", "Psychic"],
    candy_count: 100,
    multipliers: [1.59],
    spawn_chance: 0.072,
    next_evolution: [{ num: "071", name: "Victreebel" }],
    prev_evolution: [{ num: "069", name: "Bellsprout" }],
  },
  {
    id: 71,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/071.png",
    num: "071",
    name: "Victreebel",
    type: ["Grass", "Poison"],
    candy: "Bellsprout Candy",
    height: "1.70 m",
    weight: "15.5 kg",
    avg_spawns: 0.59,
    spawn_time: "12:19",
    weaknesses: ["Fire", "Ice", "Flying", "Psychic"],
    multipliers: null,
    spawn_chance: 0.0059,
    prev_evolution: [
      { num: "069", name: "Bellsprout" },
      { num: "070", name: "Weepinbell" },
    ],
  },
  {
    id: 72,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/072.png",
    num: "072",
    name: "Tentacool",
    type: ["Water", "Poison"],
    candy: "Tentacool Candy",
    height: "0.89 m",
    weight: "45.5 kg",
    avg_spawns: 81,
    spawn_time: "03:20",
    weaknesses: ["Electric", "Ground", "Psychic"],
    candy_count: 50,
    multipliers: [2.52],
    spawn_chance: 0.81,
    next_evolution: [{ num: "073", name: "Tentacruel" }],
  },
  {
    id: 73,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/073.png",
    num: "073",
    name: "Tentacruel",
    type: ["Water", "Poison"],
    candy: "Tentacool Candy",
    height: "1.60 m",
    weight: "55.0 kg",
    avg_spawns: 8.2,
    spawn_time: "23:36",
    weaknesses: ["Electric", "Ground", "Psychic"],
    multipliers: null,
    spawn_chance: 0.082,
    prev_evolution: [{ num: "072", name: "Tentacool" }],
  },
  {
    id: 74,
    egg: "2 km",
    img: "http://www.serebii.net/pokemongo/pokemon/074.png",
    num: "074",
    name: "Geodude",
    type: ["Rock", "Ground"],
    candy: "Geodude Candy",
    height: "0.41 m",
    weight: "20.0 kg",
    avg_spawns: 119,
    spawn_time: "12:40",
    weaknesses: ["Water", "Grass", "Ice", "Fighting", "Ground", "Steel"],
    candy_count: 25,
    multipliers: [1.75, 1.76],
    spawn_chance: 1.19,
    next_evolution: [
      { num: "075", name: "Graveler" },
      { num: "076", name: "Golem" },
    ],
  },
  {
    id: 75,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/075.png",
    num: "075",
    name: "Graveler",
    type: ["Rock", "Ground"],
    candy: "Geodude Candy",
    height: "0.99 m",
    weight: "105.0 kg",
    avg_spawns: 7.1,
    spawn_time: "04:53",
    weaknesses: ["Water", "Grass", "Ice", "Fighting", "Ground", "Steel"],
    candy_count: 100,
    multipliers: [1.64, 1.72],
    spawn_chance: 0.071,
    next_evolution: [{ num: "076", name: "Golem" }],
    prev_evolution: [{ num: "074", name: "Geodude" }],
  },
  {
    id: 76,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/076.png",
    num: "076",
    name: "Golem",
    type: ["Rock", "Ground"],
    candy: "Geodude Candy",
    height: "1.40 m",
    weight: "300.0 kg",
    avg_spawns: 0.47,
    spawn_time: "12:16",
    weaknesses: ["Water", "Grass", "Ice", "Fighting", "Ground", "Steel"],
    multipliers: null,
    spawn_chance: 0.0047,
    prev_evolution: [
      { num: "074", name: "Geodude" },
      { num: "075", name: "Graveler" },
    ],
  },
  {
    id: 77,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/077.png",
    num: "077",
    name: "Ponyta",
    type: ["Fire"],
    candy: "Ponyta Candy",
    height: "0.99 m",
    weight: "30.0 kg",
    avg_spawns: 51,
    spawn_time: "02:50",
    weaknesses: ["Water", "Ground", "Rock"],
    candy_count: 50,
    multipliers: [1.48, 1.5],
    spawn_chance: 0.51,
    next_evolution: [{ num: "078", name: "Rapidash" }],
  },
  {
    id: 78,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/078.png",
    num: "078",
    name: "Rapidash",
    type: ["Fire"],
    candy: "Ponyta Candy",
    height: "1.70 m",
    weight: "95.0 kg",
    avg_spawns: 1.1,
    spawn_time: "04:00",
    weaknesses: ["Water", "Ground", "Rock"],
    multipliers: null,
    spawn_chance: 0.011,
    prev_evolution: [{ num: "077", name: "Ponyta" }],
  },
  {
    id: 79,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/079.png",
    num: "079",
    name: "Slowpoke",
    type: ["Water", "Psychic"],
    candy: "Slowpoke Candy",
    height: "1.19 m",
    weight: "36.0 kg",
    avg_spawns: 105,
    spawn_time: "07:12",
    weaknesses: ["Electric", "Grass", "Bug", "Ghost", "Dark"],
    candy_count: 50,
    multipliers: [2.21],
    spawn_chance: 1.05,
    next_evolution: [{ num: "080", name: "Slowbro" }],
  },
  {
    id: 80,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/080.png",
    num: "080",
    name: "Slowbro",
    type: ["Water", "Psychic"],
    candy: "Slowpoke Candy",
    height: "1.60 m",
    weight: "78.5 kg",
    avg_spawns: 3.6,
    spawn_time: "02:56",
    weaknesses: ["Electric", "Grass", "Bug", "Ghost", "Dark"],
    multipliers: null,
    spawn_chance: 0.036,
    prev_evolution: [{ num: "079", name: "Slowpoke" }],
  },
  {
    id: 81,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/081.png",
    num: "081",
    name: "Magnemite",
    type: ["Electric"],
    candy: "Magnemite Candy",
    height: "0.30 m",
    weight: "6.0 kg",
    avg_spawns: 71,
    spawn_time: "04:04",
    weaknesses: ["Fire", "Water", "Ground"],
    candy_count: 50,
    multipliers: [2.16, 2.17],
    spawn_chance: 0.71,
    next_evolution: [{ num: "082", name: "Magneton" }],
  },
  {
    id: 82,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/082.png",
    num: "082",
    name: "Magneton",
    type: ["Electric"],
    candy: "Magnemite Candy",
    height: "0.99 m",
    weight: "60.0 kg",
    avg_spawns: 2.3,
    spawn_time: "15:25",
    weaknesses: ["Fire", "Water", "Ground"],
    multipliers: null,
    spawn_chance: 0.023,
    prev_evolution: [{ num: "081", name: "Magnemite" }],
  },
  {
    id: 83,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/083.png",
    num: "083",
    name: "Farfetch'd",
    type: ["Normal", "Flying"],
    candy: "None",
    height: "0.79 m",
    weight: "15.0 kg",
    avg_spawns: 2.12,
    spawn_time: "01:09",
    weaknesses: ["Electric", "Rock"],
    multipliers: null,
    spawn_chance: 0.0212,
  },
  {
    id: 84,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/084.png",
    num: "084",
    name: "Doduo",
    type: ["Normal", "Flying"],
    candy: "Doduo Candy",
    height: "1.40 m",
    weight: "39.2 kg",
    avg_spawns: 52,
    spawn_time: "05:10",
    weaknesses: ["Electric", "Rock"],
    candy_count: 50,
    multipliers: [2.19, 2.24],
    spawn_chance: 0.52,
    next_evolution: [{ num: "085", name: "Dodrio" }],
  },
  {
    id: 85,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/085.png",
    num: "085",
    name: "Dodrio",
    type: ["Normal", "Flying"],
    candy: "Doduo Candy",
    height: "1.80 m",
    weight: "85.2 kg",
    avg_spawns: 22,
    spawn_time: "02:12",
    weaknesses: ["Electric", "Rock"],
    multipliers: null,
    spawn_chance: 0.22,
    prev_evolution: [{ num: "084", name: "Doduo" }],
  },
  {
    id: 86,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/086.png",
    num: "086",
    name: "Seel",
    type: ["Water"],
    candy: "Seel Candy",
    height: "1.09 m",
    weight: "90.0 kg",
    avg_spawns: 28,
    spawn_time: "06:46",
    weaknesses: ["Electric", "Grass"],
    candy_count: 50,
    multipliers: [1.04, 1.96],
    spawn_chance: 0.28,
    next_evolution: [{ num: "087", name: "Dewgong" }],
  },
  {
    id: 87,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/087.png",
    num: "087",
    name: "Dewgong",
    type: ["Water", "Ice"],
    candy: "Seel Candy",
    height: "1.70 m",
    weight: "120.0 kg",
    avg_spawns: 1.3,
    spawn_time: "06:04",
    weaknesses: ["Electric", "Grass", "Fighting", "Rock"],
    multipliers: null,
    spawn_chance: 0.013,
    prev_evolution: [{ num: "086", name: "Seel" }],
  },
  {
    id: 88,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/088.png",
    num: "088",
    name: "Grimer",
    type: ["Poison"],
    candy: "Grimer Candy",
    height: "0.89 m",
    weight: "30.0 kg",
    avg_spawns: 5.2,
    spawn_time: "15:11",
    weaknesses: ["Ground", "Psychic"],
    candy_count: 50,
    multipliers: [2.44],
    spawn_chance: 0.052,
    next_evolution: [{ num: "089", name: "Muk" }],
  },
  {
    id: 89,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/089.png",
    num: "089",
    name: "Muk",
    type: ["Poison"],
    candy: "Grimer Candy",
    height: "1.19 m",
    weight: "30.0 kg",
    avg_spawns: 0.31,
    spawn_time: "01:28",
    weaknesses: ["Ground", "Psychic"],
    multipliers: null,
    spawn_chance: 0.0031,
    prev_evolution: [{ num: "088", name: "Grimer" }],
  },
  {
    id: 90,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/090.png",
    num: "090",
    name: "Shellder",
    type: ["Water"],
    candy: "Shellder Candy",
    height: "0.30 m",
    weight: "4.0 kg",
    avg_spawns: 52,
    spawn_time: "07:39",
    weaknesses: ["Electric", "Grass"],
    candy_count: 50,
    multipliers: [2.65],
    spawn_chance: 0.52,
    next_evolution: [{ num: "091", name: "Cloyster" }],
  },
  {
    id: 91,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/091.png",
    num: "091",
    name: "Cloyster",
    type: ["Water", "Ice"],
    candy: "Shellder Candy",
    height: "1.50 m",
    weight: "132.5 kg",
    avg_spawns: 1.5,
    spawn_time: "02:33",
    weaknesses: ["Electric", "Grass", "Fighting", "Rock"],
    multipliers: null,
    spawn_chance: 0.015,
    prev_evolution: [{ num: "090", name: "Shellder" }],
  },
  {
    id: 92,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/092.png",
    num: "092",
    name: "Gastly",
    type: ["Ghost", "Poison"],
    candy: "Gastly Candy",
    height: "1.30 m",
    weight: "0.1 kg",
    avg_spawns: 79,
    spawn_time: "04:21",
    weaknesses: ["Ground", "Psychic", "Ghost", "Dark"],
    candy_count: 25,
    multipliers: [1.78],
    spawn_chance: 0.79,
    next_evolution: [
      { num: "093", name: "Haunter" },
      { num: "094", name: "Gengar" },
    ],
  },
  {
    id: 93,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/093.png",
    num: "093",
    name: "Haunter",
    type: ["Ghost", "Poison"],
    candy: "Gastly Candy",
    height: "1.60 m",
    weight: "0.1 kg",
    avg_spawns: 5.2,
    spawn_time: "00:10",
    weaknesses: ["Ground", "Psychic", "Ghost", "Dark"],
    candy_count: 100,
    multipliers: [1.56, 1.8],
    spawn_chance: 0.052,
    next_evolution: [{ num: "094", name: "Gengar" }],
    prev_evolution: [{ num: "092", name: "Gastly" }],
  },
  {
    id: 94,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/094.png",
    num: "094",
    name: "Gengar",
    type: ["Ghost", "Poison"],
    candy: "Gastly Candy",
    height: "1.50 m",
    weight: "40.5 kg",
    avg_spawns: 0.67,
    spawn_time: "03:55",
    weaknesses: ["Ground", "Psychic", "Ghost", "Dark"],
    multipliers: null,
    spawn_chance: 0.0067,
    prev_evolution: [
      { num: "092", name: "Gastly" },
      { num: "093", name: "Haunter" },
    ],
  },
  {
    id: 95,
    egg: "10 km",
    img: "http://www.serebii.net/pokemongo/pokemon/095.png",
    num: "095",
    name: "Onix",
    type: ["Rock", "Ground"],
    candy: "None",
    height: "8.79 m",
    weight: "210.0 kg",
    avg_spawns: 10,
    spawn_time: "01:18",
    weaknesses: ["Water", "Grass", "Ice", "Fighting", "Ground", "Steel"],
    multipliers: null,
    spawn_chance: 0.1,
  },
  {
    id: 96,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/096.png",
    num: "096",
    name: "Drowzee",
    type: ["Psychic"],
    candy: "Drowzee Candy",
    height: "0.99 m",
    weight: "32.4 kg",
    avg_spawns: 321,
    spawn_time: "01:51",
    weaknesses: ["Bug", "Ghost", "Dark"],
    candy_count: 50,
    multipliers: [2.08, 2.09],
    spawn_chance: 3.21,
    next_evolution: [{ num: "097", name: "Hypno" }],
  },
  {
    id: 97,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/097.png",
    num: "097",
    name: "Hypno",
    type: ["Psychic"],
    candy: "Drowzee Candy",
    height: "1.60 m",
    weight: "75.6 kg",
    avg_spawns: 10,
    spawn_time: "02:17",
    weaknesses: ["Bug", "Ghost", "Dark"],
    multipliers: null,
    spawn_chance: 0.1,
    prev_evolution: [{ num: "096", name: "Drowzee" }],
  },
  {
    id: 98,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/098.png",
    num: "098",
    name: "Krabby",
    type: ["Water"],
    candy: "Krabby Candy",
    height: "0.41 m",
    weight: "6.5 kg",
    avg_spawns: 212,
    spawn_time: "03:33",
    weaknesses: ["Electric", "Grass"],
    candy_count: 50,
    multipliers: [2.36, 2.4],
    spawn_chance: 2.12,
    next_evolution: [{ num: "099", name: "Kingler" }],
  },
  {
    id: 99,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/099.png",
    num: "099",
    name: "Kingler",
    type: ["Water"],
    candy: "Krabby Candy",
    height: "1.30 m",
    weight: "60.0 kg",
    avg_spawns: 6.2,
    spawn_time: "03:44",
    weaknesses: ["Electric", "Grass"],
    multipliers: null,
    spawn_chance: 0.062,
    prev_evolution: [{ num: "098", name: "Krabby" }],
  },
  {
    id: 100,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/100.png",
    num: "100",
    name: "Voltorb",
    type: ["Electric"],
    candy: "Voltorb Candy",
    height: "0.51 m",
    weight: "10.4 kg",
    avg_spawns: 65,
    spawn_time: "04:36",
    weaknesses: ["Ground"],
    candy_count: 50,
    multipliers: [2.01, 2.02],
    spawn_chance: 0.65,
    next_evolution: [{ num: "101", name: "Electrode" }],
  },
  {
    id: 101,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/101.png",
    num: "101",
    name: "Electrode",
    type: ["Electric"],
    candy: "Voltorb Candy",
    height: "1.19 m",
    weight: "66.6 kg",
    avg_spawns: 2,
    spawn_time: "04:10",
    weaknesses: ["Ground"],
    multipliers: null,
    spawn_chance: 0.02,
    prev_evolution: [{ num: "100", name: "Voltorb" }],
  },
  {
    id: 102,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/102.png",
    num: "102",
    name: "Exeggcute",
    type: ["Grass", "Psychic"],
    candy: "Exeggcute Candy",
    height: "0.41 m",
    weight: "2.5 kg",
    avg_spawns: 78,
    spawn_time: "09:09",
    weaknesses: ["Fire", "Ice", "Poison", "Flying", "Bug", "Ghost", "Dark"],
    candy_count: 50,
    multipliers: [2.7, 3.18],
    spawn_chance: 0.78,
    next_evolution: [{ num: "103", name: "Exeggutor" }],
  },
  {
    id: 103,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/103.png",
    num: "103",
    name: "Exeggutor",
    type: ["Grass", "Psychic"],
    candy: "Exeggcute Candy",
    height: "2.01 m",
    weight: "120.0 kg",
    avg_spawns: 1.4,
    spawn_time: "12:34",
    weaknesses: ["Fire", "Ice", "Poison", "Flying", "Bug", "Ghost", "Dark"],
    multipliers: null,
    spawn_chance: 0.014,
    prev_evolution: [{ num: "102", name: "Exeggcute" }],
  },
  {
    id: 104,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/104.png",
    num: "104",
    name: "Cubone",
    type: ["Ground"],
    candy: "Cubone Candy",
    height: "0.41 m",
    weight: "6.5 kg",
    avg_spawns: 61,
    spawn_time: "01:51",
    weaknesses: ["Water", "Grass", "Ice"],
    candy_count: 50,
    multipliers: [1.67],
    spawn_chance: 0.61,
    next_evolution: [{ num: "105", name: "Marowak" }],
  },
  {
    id: 105,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/105.png",
    num: "105",
    name: "Marowak",
    type: ["Ground"],
    candy: "Cubone Candy",
    height: "0.99 m",
    weight: "45.0 kg",
    avg_spawns: 2,
    spawn_time: "03:59",
    weaknesses: ["Water", "Grass", "Ice"],
    multipliers: null,
    spawn_chance: 0.02,
    prev_evolution: [{ num: "104", name: "Cubone" }],
  },
  {
    id: 106,
    egg: "10 km",
    img: "http://www.serebii.net/pokemongo/pokemon/106.png",
    num: "106",
    name: "Hitmonlee",
    type: ["Fighting"],
    candy: "None",
    height: "1.50 m",
    weight: "49.8 kg",
    avg_spawns: 2,
    spawn_time: "03:59",
    weaknesses: ["Flying", "Psychic", "Fairy"],
    multipliers: null,
    spawn_chance: 0.02,
  },
  {
    id: 107,
    egg: "10 km",
    img: "http://www.serebii.net/pokemongo/pokemon/107.png",
    num: "107",
    name: "Hitmonchan",
    type: ["Fighting"],
    candy: "None",
    height: "1.40 m",
    weight: "50.2 kg",
    avg_spawns: 2.2,
    spawn_time: "05:58",
    weaknesses: ["Flying", "Psychic", "Fairy"],
    multipliers: null,
    spawn_chance: 0.022,
  },
  {
    id: 108,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/108.png",
    num: "108",
    name: "Lickitung",
    type: ["Normal"],
    candy: "None",
    height: "1.19 m",
    weight: "65.5 kg",
    avg_spawns: 1.1,
    spawn_time: "02:46",
    weaknesses: ["Fighting"],
    multipliers: null,
    spawn_chance: 0.011,
  },
  {
    id: 109,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/109.png",
    num: "109",
    name: "Koffing",
    type: ["Poison"],
    candy: "Koffing Candy",
    height: "0.61 m",
    weight: "1.0 kg",
    avg_spawns: 20,
    spawn_time: "08:16",
    weaknesses: ["Ground", "Psychic"],
    candy_count: 50,
    multipliers: [1.11],
    spawn_chance: 0.2,
    next_evolution: [{ num: "110", name: "Weezing" }],
  },
  {
    id: 110,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/110.png",
    num: "110",
    name: "Weezing",
    type: ["Poison"],
    candy: "Koffing Candy",
    height: "1.19 m",
    weight: "9.5 kg",
    avg_spawns: 1.6,
    spawn_time: "12:17",
    weaknesses: ["Ground", "Psychic"],
    multipliers: null,
    spawn_chance: 0.016,
    prev_evolution: [{ num: "109", name: "Koffing" }],
  },
  {
    id: 111,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/111.png",
    num: "111",
    name: "Rhyhorn",
    type: ["Ground", "Rock"],
    candy: "Rhyhorn Candy",
    height: "0.99 m",
    weight: "115.0 kg",
    avg_spawns: 63,
    spawn_time: "03:21",
    weaknesses: ["Water", "Grass", "Ice", "Fighting", "Ground", "Steel"],
    candy_count: 50,
    multipliers: [1.91],
    spawn_chance: 0.63,
    next_evolution: [{ num: "112", name: "Rhydon" }],
  },
  {
    id: 112,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/112.png",
    num: "112",
    name: "Rhydon",
    type: ["Ground", "Rock"],
    candy: "Rhyhorn Candy",
    height: "1.91 m",
    weight: "120.0 kg",
    avg_spawns: 2.2,
    spawn_time: "05:50",
    weaknesses: ["Water", "Grass", "Ice", "Fighting", "Ground", "Steel"],
    multipliers: null,
    spawn_chance: 0.022,
    prev_evolution: [{ num: "111", name: "Rhyhorn" }],
  },
  {
    id: 113,
    egg: "10 km",
    img: "http://www.serebii.net/pokemongo/pokemon/113.png",
    num: "113",
    name: "Chansey",
    type: ["Normal"],
    candy: "None",
    height: "1.09 m",
    weight: "34.6 kg",
    avg_spawns: 1.3,
    spawn_time: "04:46",
    weaknesses: ["Fighting"],
    multipliers: null,
    spawn_chance: 0.013,
  },
  {
    id: 114,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/114.png",
    num: "114",
    name: "Tangela",
    type: ["Grass"],
    candy: "None",
    height: "0.99 m",
    weight: "35.0 kg",
    avg_spawns: 22.8,
    spawn_time: "23:13",
    weaknesses: ["Fire", "Ice", "Poison", "Flying", "Bug"],
    multipliers: null,
    spawn_chance: 0.228,
  },
  {
    id: 115,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/115.png",
    num: "115",
    name: "Kangaskhan",
    type: ["Normal"],
    candy: "None",
    height: "2.21 m",
    weight: "80.0 kg",
    avg_spawns: 0.86,
    spawn_time: "02:40",
    weaknesses: ["Fighting"],
    multipliers: null,
    spawn_chance: 0.0086,
  },
  {
    id: 116,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/116.png",
    num: "116",
    name: "Horsea",
    type: ["Water"],
    candy: "Horsea Candy",
    height: "0.41 m",
    weight: "8.0 kg",
    avg_spawns: 113,
    spawn_time: "02:53",
    weaknesses: ["Electric", "Grass"],
    candy_count: 50,
    multipliers: [2.23],
    spawn_chance: 1.13,
    next_evolution: [{ num: "117", name: "Seadra" }],
  },
  {
    id: 117,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/117.png",
    num: "117",
    name: "Seadra",
    type: ["Water"],
    candy: "Horsea Candy",
    height: "1.19 m",
    weight: "25.0 kg",
    avg_spawns: 3.4,
    spawn_time: "03:18",
    weaknesses: ["Electric", "Grass"],
    multipliers: null,
    spawn_chance: 0.034,
    prev_evolution: [{ num: "116", name: "Horsea" }],
  },
  {
    id: 118,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/118.png",
    num: "118",
    name: "Goldeen",
    type: ["Water"],
    candy: "Goldeen Candy",
    height: "0.61 m",
    weight: "15.0 kg",
    avg_spawns: 218,
    spawn_time: "03:14",
    weaknesses: ["Electric", "Grass"],
    candy_count: 50,
    multipliers: [2.15, 2.2],
    spawn_chance: 2.18,
    next_evolution: [{ num: "119", name: "Seaking" }],
  },
  {
    id: 119,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/119.png",
    num: "119",
    name: "Seaking",
    type: ["Water"],
    candy: "Goldeen Candy",
    height: "1.30 m",
    weight: "39.0 kg",
    avg_spawns: 8,
    spawn_time: "05:21",
    weaknesses: ["Electric", "Grass"],
    multipliers: null,
    spawn_chance: 0.08,
    prev_evolution: [{ num: "118", name: "Goldeen" }],
  },
  {
    id: 120,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/120.png",
    num: "120",
    name: "Staryu",
    type: ["Water"],
    candy: "Staryu Candy",
    height: "0.79 m",
    weight: "34.5 kg",
    avg_spawns: 195,
    spawn_time: "22:59",
    weaknesses: ["Electric", "Grass"],
    candy_count: 50,
    multipliers: [2.38, 2.41],
    spawn_chance: 1.95,
    next_evolution: [{ num: "121", name: "Starmie" }],
  },
  {
    id: 121,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/121.png",
    num: "121",
    name: "Starmie",
    type: ["Water", "Psychic"],
    candy: "Staryu Candy",
    height: "1.09 m",
    weight: "80.0 kg",
    avg_spawns: 3.4,
    spawn_time: "06:57",
    weaknesses: ["Electric", "Grass", "Bug", "Ghost", "Dark"],
    multipliers: null,
    spawn_chance: 0.034,
    prev_evolution: [{ num: "120", name: "Staryu" }],
  },
  {
    id: 122,
    egg: "10 km",
    img: "http://www.serebii.net/pokemongo/pokemon/122.png",
    num: "122",
    name: "Mr. Mime",
    type: ["Psychic"],
    candy: "None",
    height: "1.30 m",
    weight: "54.5 kg",
    avg_spawns: 0.31,
    spawn_time: "01:51",
    weaknesses: ["Bug", "Ghost", "Dark"],
    multipliers: null,
    spawn_chance: 0.0031,
  },
  {
    id: 123,
    egg: "10 km",
    img: "http://www.serebii.net/pokemongo/pokemon/123.png",
    num: "123",
    name: "Scyther",
    type: ["Bug", "Flying"],
    candy: "None",
    height: "1.50 m",
    weight: "56.0 kg",
    avg_spawns: 14,
    spawn_time: "05:43",
    weaknesses: ["Fire", "Electric", "Ice", "Flying", "Rock"],
    multipliers: null,
    spawn_chance: 0.14,
  },
  {
    id: 124,
    egg: "10 km",
    img: "http://www.serebii.net/pokemongo/pokemon/124.png",
    num: "124",
    name: "Jynx",
    type: ["Ice", "Psychic"],
    candy: "None",
    height: "1.40 m",
    weight: "40.6 kg",
    avg_spawns: 35,
    spawn_time: "05:41",
    weaknesses: ["Fire", "Bug", "Rock", "Ghost", "Dark", "Steel"],
    multipliers: null,
    spawn_chance: 0.35,
  },
  {
    id: 125,
    egg: "10 km",
    img: "http://www.serebii.net/pokemongo/pokemon/125.png",
    num: "125",
    name: "Electabuzz",
    type: ["Electric"],
    candy: "None",
    height: "1.09 m",
    weight: "30.0 kg",
    avg_spawns: 7.4,
    spawn_time: "04:28",
    weaknesses: ["Ground"],
    multipliers: null,
    spawn_chance: 0.074,
  },
  {
    id: 126,
    egg: "10 km",
    img: "http://www.serebii.net/pokemongo/pokemon/126.png",
    num: "126",
    name: "Magmar",
    type: ["Fire"],
    candy: "None",
    height: "1.30 m",
    weight: "44.5 kg",
    avg_spawns: 10,
    spawn_time: "20:36",
    weaknesses: ["Water", "Ground", "Rock"],
    multipliers: null,
    spawn_chance: 0.1,
  },
  {
    id: 127,
    egg: "10 km",
    img: "http://www.serebii.net/pokemongo/pokemon/127.png",
    num: "127",
    name: "Pinsir",
    type: ["Bug"],
    candy: "None",
    height: "1.50 m",
    weight: "55.0 kg",
    avg_spawns: 99,
    spawn_time: "03:25",
    weaknesses: ["Fire", "Flying", "Rock"],
    multipliers: null,
    spawn_chance: 0.99,
  },
  {
    id: 128,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/128.png",
    num: "128",
    name: "Tauros",
    type: ["Normal"],
    candy: "None",
    height: "1.40 m",
    weight: "88.4 kg",
    avg_spawns: 12,
    spawn_time: "00:37",
    weaknesses: ["Fighting"],
    multipliers: null,
    spawn_chance: 0.12,
  },
  {
    id: 129,
    egg: "2 km",
    img: "http://www.serebii.net/pokemongo/pokemon/129.png",
    num: "129",
    name: "Magikarp",
    type: ["Water"],
    candy: "Magikarp Candy",
    height: "0.89 m",
    weight: "10.0 kg",
    avg_spawns: 478,
    spawn_time: "14:26",
    weaknesses: ["Electric", "Grass"],
    candy_count: 400,
    multipliers: [10.1, 11.8],
    spawn_chance: 4.78,
    next_evolution: [{ num: "130", name: "Gyarados" }],
  },
  {
    id: 130,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/130.png",
    num: "130",
    name: "Gyarados",
    type: ["Water", "Flying"],
    candy: "Magikarp Candy",
    height: "6.50 m",
    weight: "235.0 kg",
    avg_spawns: 0.32,
    spawn_time: "02:15",
    weaknesses: ["Electric", "Rock"],
    multipliers: null,
    spawn_chance: 0.0032,
    prev_evolution: [{ num: "129", name: "Magikarp" }],
  },
  {
    id: 131,
    egg: "10 km",
    img: "http://www.serebii.net/pokemongo/pokemon/131.png",
    num: "131",
    name: "Lapras",
    type: ["Water", "Ice"],
    candy: "None",
    height: "2.49 m",
    weight: "220.0 kg",
    avg_spawns: 0.6,
    spawn_time: "08:59",
    weaknesses: ["Electric", "Grass", "Fighting", "Rock"],
    multipliers: null,
    spawn_chance: 0.006,
  },
  {
    id: 132,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/132.png",
    num: "132",
    name: "Ditto",
    type: ["Normal"],
    candy: "None",
    height: "0.30 m",
    weight: "4.0 kg",
    avg_spawns: 0,
    spawn_time: "N/A",
    weaknesses: ["Fighting"],
    multipliers: null,
    spawn_chance: 0,
  },
  {
    id: 133,
    egg: "10 km",
    img: "http://www.serebii.net/pokemongo/pokemon/133.png",
    num: "133",
    name: "Eevee",
    type: ["Normal"],
    candy: "Eevee Candy",
    height: "0.30 m",
    weight: "6.5 kg",
    avg_spawns: 275,
    spawn_time: "05:32",
    weaknesses: ["Fighting"],
    candy_count: 25,
    multipliers: [2.02, 2.64],
    spawn_chance: 2.75,
    next_evolution: [
      { num: "134", name: "Vaporeon" },
      { num: "135", name: "Jolteon" },
      { num: "136", name: "Flareon" },
    ],
  },
  {
    id: 134,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/134.png",
    num: "134",
    name: "Vaporeon",
    type: ["Water"],
    candy: "Eevee Candy",
    height: "0.99 m",
    weight: "29.0 kg",
    avg_spawns: 1.4,
    spawn_time: "10:54",
    weaknesses: ["Electric", "Grass"],
    multipliers: null,
    spawn_chance: 0.014,
    prev_evolution: [{ num: "133", name: "Eevee" }],
  },
  {
    id: 135,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/135.png",
    num: "135",
    name: "Jolteon",
    type: ["Electric"],
    candy: "None",
    height: "0.79 m",
    weight: "24.5 kg",
    avg_spawns: 1.2,
    spawn_time: "02:30",
    weaknesses: ["Ground"],
    multipliers: null,
    spawn_chance: 0.012,
    prev_evolution: [{ num: "133", name: "Eevee" }],
  },
  {
    id: 136,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/136.png",
    num: "136",
    name: "Flareon",
    type: ["Fire"],
    candy: "Eevee Candy",
    height: "0.89 m",
    weight: "25.0 kg",
    avg_spawns: 1.7,
    spawn_time: "07:02",
    weaknesses: ["Water", "Ground", "Rock"],
    multipliers: null,
    spawn_chance: 0.017,
    prev_evolution: [{ num: "133", name: "Eevee" }],
  },
  {
    id: 137,
    egg: "5 km",
    img: "http://www.serebii.net/pokemongo/pokemon/137.png",
    num: "137",
    name: "Porygon",
    type: ["Normal"],
    candy: "None",
    height: "0.79 m",
    weight: "36.5 kg",
    avg_spawns: 1.2,
    spawn_time: "02:49",
    weaknesses: ["Fighting"],
    multipliers: null,
    spawn_chance: 0.012,
  },
  {
    id: 138,
    egg: "10 km",
    img: "http://www.serebii.net/pokemongo/pokemon/138.png",
    num: "138",
    name: "Omanyte",
    type: ["Rock", "Water"],
    candy: "Omanyte Candy",
    height: "0.41 m",
    weight: "7.5 kg",
    avg_spawns: 14,
    spawn_time: "10:23",
    weaknesses: ["Electric", "Grass", "Fighting", "Ground"],
    candy_count: 50,
    multipliers: [2.12],
    spawn_chance: 0.14,
    next_evolution: [{ num: "139", name: "Omastar" }],
  },
  {
    id: 139,
    egg: "Omanyte Candy",
    img: "http://www.serebii.net/pokemongo/pokemon/139.png",
    num: "139",
    name: "Omastar",
    type: ["Rock", "Water"],
    candy: "None",
    height: "0.99 m",
    weight: "35.0 kg",
    avg_spawns: 0.61,
    spawn_time: "05:04",
    weaknesses: ["Electric", "Grass", "Fighting", "Ground"],
    multipliers: null,
    spawn_chance: 0.0061,
    prev_evolution: [{ num: "138", name: "Omanyte" }],
  },
  {
    id: 140,
    egg: "10 km",
    img: "http://www.serebii.net/pokemongo/pokemon/140.png",
    num: "140",
    name: "Kabuto",
    type: ["Rock", "Water"],
    candy: "Kabuto Candy",
    height: "0.51 m",
    weight: "11.5 kg",
    avg_spawns: 10,
    spawn_time: "00:05",
    weaknesses: ["Electric", "Grass", "Fighting", "Ground"],
    candy_count: 50,
    multipliers: [1.97, 2.37],
    spawn_chance: 0.1,
    next_evolution: [{ num: "141", name: "Kabutops" }],
  },
  {
    id: 141,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/141.png",
    num: "141",
    name: "Kabutops",
    type: ["Rock", "Water"],
    candy: "Kabuto Candy",
    height: "1.30 m",
    weight: "40.5 kg",
    avg_spawns: 0.32,
    spawn_time: "23:40",
    weaknesses: ["Electric", "Grass", "Fighting", "Ground"],
    multipliers: null,
    spawn_chance: 0.0032,
    prev_evolution: [{ num: "140", name: "Kabuto" }],
  },
  {
    id: 142,
    egg: "10 km",
    img: "http://www.serebii.net/pokemongo/pokemon/142.png",
    num: "142",
    name: "Aerodactyl",
    type: ["Rock", "Flying"],
    candy: "None",
    height: "1.80 m",
    weight: "59.0 kg",
    avg_spawns: 1.8,
    spawn_time: "23:40",
    weaknesses: ["Water", "Electric", "Ice", "Rock", "Steel"],
    multipliers: null,
    spawn_chance: 0.018,
  },
  {
    id: 143,
    egg: "10 km",
    img: "http://www.serebii.net/pokemongo/pokemon/143.png",
    num: "143",
    name: "Snorlax",
    type: ["Normal"],
    candy: "None",
    height: "2.11 m",
    weight: "460.0 kg",
    avg_spawns: 1.6,
    spawn_time: "23:40",
    weaknesses: ["Fighting"],
    multipliers: null,
    spawn_chance: 0.016,
  },
  {
    id: 144,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/144.png",
    num: "144",
    name: "Articuno",
    type: ["Ice", "Flying"],
    candy: "None",
    height: "1.70 m",
    weight: "55.4 kg",
    avg_spawns: 0,
    spawn_time: "N/A",
    weaknesses: ["Fire", "Electric", "Rock", "Steel"],
    multipliers: null,
    spawn_chance: 0,
  },
  {
    id: 145,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/145.png",
    num: "145",
    name: "Zapdos",
    type: ["Electric", "Flying"],
    candy: "None",
    height: "1.60 m",
    weight: "52.6 kg",
    avg_spawns: 0,
    spawn_time: "N/A",
    weaknesses: ["Ice", "Rock"],
    multipliers: null,
    spawn_chance: 0,
  },
  {
    id: 146,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/146.png",
    num: "146",
    name: "Moltres",
    type: ["Fire", "Flying"],
    candy: "None",
    height: "2.01 m",
    weight: "60.0 kg",
    avg_spawns: 0,
    spawn_time: "N/A",
    weaknesses: ["Water", "Electric", "Rock"],
    multipliers: null,
    spawn_chance: 0,
  },
  {
    id: 147,
    egg: "10 km",
    img: "http://www.serebii.net/pokemongo/pokemon/147.png",
    num: "147",
    name: "Dratini",
    type: ["Dragon"],
    candy: "Dratini Candy",
    height: "1.80 m",
    weight: "3.3 kg",
    avg_spawns: 30,
    spawn_time: "06:41",
    weaknesses: ["Ice", "Dragon", "Fairy"],
    candy_count: 25,
    multipliers: [1.83, 1.84],
    spawn_chance: 0.3,
    next_evolution: [
      { num: "148", name: "Dragonair" },
      { num: "149", name: "Dragonite" },
    ],
  },
  {
    id: 148,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/148.png",
    num: "148",
    name: "Dragonair",
    type: ["Dragon"],
    candy: "Dratini Candy",
    height: "3.99 m",
    weight: "16.5 kg",
    avg_spawns: 2,
    spawn_time: "11:57",
    weaknesses: ["Ice", "Dragon", "Fairy"],
    candy_count: 100,
    multipliers: [2.05],
    spawn_chance: 0.02,
    next_evolution: [{ num: "149", name: "Dragonite" }],
    prev_evolution: [{ num: "147", name: "Dratini" }],
  },
  {
    id: 149,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/149.png",
    num: "149",
    name: "Dragonite",
    type: ["Dragon", "Flying"],
    candy: "Dratini Candy",
    height: "2.21 m",
    weight: "210.0 kg",
    avg_spawns: 0.11,
    spawn_time: "23:38",
    weaknesses: ["Ice", "Rock", "Dragon", "Fairy"],
    multipliers: null,
    spawn_chance: 0.0011,
    prev_evolution: [
      { num: "147", name: "Dratini" },
      { num: "148", name: "Dragonair" },
    ],
  },
  {
    id: 150,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/150.png",
    num: "150",
    name: "Mewtwo",
    type: ["Psychic"],
    candy: "None",
    height: "2.01 m",
    weight: "122.0 kg",
    avg_spawns: 0,
    spawn_time: "N/A",
    weaknesses: ["Bug", "Ghost", "Dark"],
    multipliers: null,
    spawn_chance: 0,
  },
  {
    id: 151,
    egg: "Not in Eggs",
    img: "http://www.serebii.net/pokemongo/pokemon/151.png",
    num: "151",
    name: "Mew",
    type: ["Psychic"],
    candy: "None",
    height: "0.41 m",
    weight: "4.0 kg",
    avg_spawns: 0,
    spawn_time: "N/A",
    weaknesses: ["Bug", "Ghost", "Dark"],
    multipliers: null,
    spawn_chance: 0,
  },
];
